name: influto_example
description: Minimal example app for the InfluTo Flutter SDK.
publish_to: none
version: 1.0.0

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  influto:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
